# Generated by Django 5.1.7 on 2025-05-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditEntry',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
