# Generated by Django 5.1.7 on 2025-03-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_capacity', models.PositiveIntegerField(help_text='Capacidade máxima em kg')),
                ('cost_per_km', models.DecimalField(decimal_places=2, help_text='Custo por km rodado', max_digits=10)),
            ],
        ),
    ]
