# Generated by Django 5.1.7 on 2025-05-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='valid',
            field=models.BooleanField(default=False, help_text='Indica se os dados do motorista foram validados'),
        ),
    ]
